const works = [
  {
    title: "Doctor's App Reservations",
    description: "Doctor Reservation Project is a Web app that allows you to make doctor's appointments, Front-End built with: React Redux. For the Back-End, we created an API with Ruby & Rails and deployed it using Render.",
    featured: 'https://user-images.githubusercontent.com/34493013/215590770-d6ad296e-6c38-483b-a6d3-5c018b116ce0.png',
    technologies: [
      'Ruby on rails',
      'React Redux',
      'PostgreSQL',
      'API',
    ],
    linkLive: 'https://stately-sunflower-3e9b13.netlify.app/',
    linkSource: 'https://github.com/carlosmuerto/doctor_reservation_page/',
  },
  {
    title: 'HeathStone Card categorized',
    description: "On this page, My task is to build a web application that consumes rapidapi.com's hearthstone Restful API. The application will show all HearthStone cards categorized in different ways.",
    featured: 'https://user-images.githubusercontent.com/34493013/217884726-6e649f1f-817a-4f9c-a019-c8ebb1e3aad6.png',
    technologies: [
      'rapidapi.com',
      'SCSS',
      'ReactJS Redux',
      'Restful API',
    ],
    linkLive: 'https://sweet-scone-b12e3d.netlify.app/',
    linkSource: 'https://github.com/carlosmuerto/simple-FMP-page',
  },
  {
    title: 'Math Magicians and Calculator',
    description: '"Math magicians" is a website for all fans of mathematics. It is a Single Page App (SPA) that allows users to: Make simple calculations and Read a random math-related quote.',
    featured: 'https://user-images.githubusercontent.com/34493013/217883697-4ca94ce5-bfab-44e2-9371-6186e9347a38.png',
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
      'ReactJS',
    ],
    linkLive: 'https://luxury-tapioca-4b5422.netlify.app/',
    linkSource: 'https://github.com/carlosmuerto/Math-Magicians',
  },
  {
    title: 'online website for a conference',
    description: 'This capstone project is based on an online website for a conference. The content was randomly generated by pages on the internet. Built with HTML, SCSS and JavaScript.',
    featured: 'https://user-images.githubusercontent.com/34493013/217887746-98ffcf1a-c280-45bb-b7f7-0f1328165a88.png',
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
      'SCSS preprocessor'
    ],
    linkLive: 'https://carlosmuerto.github.io/capstone-project-conference-page/',
    linkSource: 'https://github.com/carlosmuerto/capstone-project-conference-page',
  },
  {
    title: 'Awesome books: with ES6',
    description: '"Awesome books" is a simple interactive website that displays a list of books and allows you to add and remove books from that list. It is built with JavaScript for DOM manipulation and for managing data in objects. ',
    featured: 'https://user-images.githubusercontent.com/34493013/217900370-c388ef4c-a5df-4cbc-a8ea-c2d2f961b291.png',
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
      'luxon',
      'SPA',
    ],
    linkLive: 'https://carlosmuerto.github.io/Awesome-books-ES6/',
    linkSource: 'https://github.com/carlosmuerto/Awesome-books-ES6',
  },
  {
    title: 'To Do list: with Webpack',
    description: 'In this project, I will build a simple HTML list of To-Do tasks. This simple web page will be built using Webpack and served by a Webpack dev server.',
    featured: 'https://user-images.githubusercontent.com/34493013/217900778-56b1abd8-ffd6-4166-85de-87d134a1be20.png',
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
      'luxon',
      'webpack',
      'SPA',
    ],
    linkLive: 'https://carlosmuerto.github.io/to-do-list-webpack/',
    linkSource: 'https://github.com/carlosmuerto/to-do-list-webpack',
  },
  
];

/*


  {
    title: '',
    description: '',
    featured: '',
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
      'ReactJS',
    ],
    linkLive: '',
    linkSource: '',
  },


*/

export default works;